name: bcrypt
description: This package use jBCrypt modified code to work with Dart VM.
version: 1.2.0
repository: https://github.com/astudilloalex/dart-bcrypt
# homepage: https://www.example.com

environment:
  sdk: '>=3.7.0 <4.0.0'
  
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.28.0
